Controllers/CustomersController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrashCollection.Models;

namespace TrashCollection.Controllers
{
    public class CustomersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? CustomerId)
        {
            string userId = User.Identity.GetUserId();

            var customer = db.Customers.Where(m => m.ApplicationId == userId).SingleOrDefault();

            return View(customer);
            /* if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
              }
        
            */
            }    
            // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FirstName,LastName,Email, pickUpAddress, billingAddress, dayOfWeek")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                customer.ApplicationId = userId;
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int CustomerId)
        {
            string userId = User.Identity.GetUserId();

            Customer customer = db.Customers.Where(m => m.ApplicationId == userId).SingleOrDefault();
           
            if (customer == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
         
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FirstName,LastName,Email,pickUpAdress,billingAddress,balance,dayOfWeek,oneTimePickUpDate,startDate,endDate")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int CustomerId)
        {
            
            Customer customer = db.Customers.Find(CustomerId);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int CustomerId)
        {
            Customer customer = db.Customers.Find(CustomerId);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void setDayOfWeek()
        {



        }
    }
}

Controllers/EmployeesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Xml.Linq;
using TrashCollection.Models;

namespace TrashCollection.Controllers
{
    public class EmployeesController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        List<Customer> pickupList;
        Employee employee = new Employee();
   
        // GET: Employees
        public ActionResult Index(int? CustomerId)
        { 
            var user = db.Customers.Where(u => u.CustomerId == CustomerId).Include(m => m.ApplicationUser).FirstOrDefault();
            pickupList = new List<Customer>();

            DayOfWeek dayOfWeek = new DayOfWeek();

       
            foreach (Customer customer in db.Customers)
            {
                if (employee.Zip == customer.Zip)
                {
                    //if (customer.pickupDate.ToString() == DateTime.Now.ToString())
                    if (customer.dayOfWeek == DayOfWeek.Monday && user.dayOfWeek == DayOfWeek.Monday)
                    {
                        pickupList.Add(customer);
                        return View(pickupList);
                    }
                    else if (customer.dayOfWeek == DayOfWeek.Tuesday && user.dayOfWeek == DayOfWeek.Tuesday)
                    {
                        pickupList.Add(customer);
                        return View(pickupList);
                    }
                    else if (customer.dayOfWeek == DayOfWeek.Wednesday && user.dayOfWeek == DayOfWeek.Wednesday)
                    {
                        pickupList.Add(customer);
                        return View(pickupList);
                    }
                    else if (customer.dayOfWeek == DayOfWeek.Thursday && user.dayOfWeek == DayOfWeek.Thursday)
                    {
                        pickupList.Add(customer);
                        return View(pickupList);
                    }
                    else if (customer.dayOfWeek == DayOfWeek.Friday && user.dayOfWeek == DayOfWeek.Friday)
                    {
                        pickupList.Add(customer);
                        return View(pickupList);
                    }
                    else if (customer.dayOfWeek == DayOfWeek.Saturday && user.dayOfWeek == DayOfWeek.Saturday)
                    {
                        pickupList.Add(customer);
                        return View(pickupList);
                    }
                }
                return View(pickupList);
            }
            return View(pickupList);
        }

        public bool PickedUp(Customer customer, bool isPickedUp)
        {
            int newBalance = (customer.balance + 10);
            customer.balance = newBalance;

            
            return (isPickedUp == true);
        }

        // GET: Employees/Details/5
        public ActionResult Details(int CustomerId)
        {
            if (CustomerId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(CustomerId);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FirstName,LastName,Address,PhoneNumber")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                employee.ApplicationId = userId;
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FirstName,LastName,Address,PhoneNumber")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

      
        [HttpGet]

        public ActionResult Map()
        {
            Address address = new Address();

            foreach (Customer customer in db.Customers)
            {
                //if (customer.pickupDate.ToString() == DateTime.Now.ToString())
               

                //pickupList.Add(customer);
                //return View(pickuplist);

                        //}
                        //foreach (var customer in pickupList)
                        //{

                var url = string.Format("http://maps.google.com/maps/geo?q={0}+{1}+{2}+{3}+{4}&output=xml&oe=utf8&sensor=false&key={5}", customer.Address1, customer.City, ", ", customer.State, customer.Zip, API.Keys.GoogleKey);
                var webClient = new WebClient();

                WebRequest request = WebRequest.Create(url);
                WebResponse response = request.GetResponse();
                XDocument xdoc = XDocument.Load(response.GetResponseStream());

                XElement result = xdoc.Element("GeocodeResponse").Element("result");
                XElement locationElement = result.Element("geometry").Element("location");
                XElement lat = locationElement.Element("lat");
                XElement lng = locationElement.Element("lng");
            }

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_CustomerLayout.cshtml
@{
    ViewBag.Title = "_CustomerLayout";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Coles Country Municipal Disposal Program</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CCMDS", "Pickups", "Map", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Pickups", "Index", "Employees")</li>
                    <li>@Html.ActionLink("Map", "Map", "Employees")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Coles Country Municipal Disposal Program</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_EmployeeLayout.cshtml
@{
    ViewBag.Title = "_EmployeeLayout";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Coles Country Municipal Disposal Program</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CCMDS", "Pickups", "Map", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Pickups", "Index", "Employees")</li>
                    <li>@Html.ActionLink("Map", "Map", "Employees")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Coles Country Municipal Disposal Program</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Coles Country Municipal Disposal Program</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CCMDS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Your Account", "Details", "Customers")</li>
                    <li>@Html.ActionLink("Pay Bill", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Coles Country Municipal Disposal Program</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>